### ISSUE TITLE
[TweenPlayer] - How to move button position by delta

### ISSUE THREAD

**Issue by unitydev2019** [yuyang9119/UnityAssetStoreSupport#5]
Hi! I just buy the TweenPlayer and want to set up the button to move 100px from the left to the designed position
Please help me to do this. In current setup of "Transform Position", there are only fixed F and T, so that every I change the 
designed position of the button, I must remove the component and add it again to let the F and T know a new position.
Thanks!

**Comment by YT-GameMaker** [comment]
Hi, you can use context menu to copy current button position:

[cid:image001.png@01D674F5.D4AB6460]

Click the context menu button (see the red circles), you’ll see a popup menu, then you can use these menu commands to copy data between target and Tween Player:

[cid:image002.png@01D674F8.2C597560]

发件人: unitydev2019<mailto:notifications@github.com>
发送时间: 2020年8月18日 0:18
收件人: yuyang9119/UnityAssetStoreSupport<mailto:UnityAssetStoreSupport@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [yuyang9119/UnityAssetStoreSupport] [TweenPlayer] - How to move button position by delta (#5)


Hi! I just buy the TweenPlayer and want to set up the button to move 100px from the left to the designed position
Please help me to do this. In current setup of "Transform Position", there are only fixed F and T, so that every I change the
designed position of the button, I must remove the component and add it again to let the F and T know a new position.
Thanks!

―

**Comment by unitydev2019** [comment]
Thank you! I will try it! But it is awesome if you can support the delta feature.
I have other questions:

1. When I setting the time to 1s and press play, I can not see the movement. It seems the loading screen makes that move stuck
(Because when I change the moving time to 2s, I can see that). How can I fix that? What is the best way to preload or cache the tween before it showing and start?
2. How can I set the delay from the start of an animation?
Thanks!

**Comment by YT-GameMaker** [comment]
1.    You can wait a few seconds then enable the Tween Player, but real game is faster than editor, so you needn’t wait too long.

2.    If you want to delay one animation item of Tween Player, you can set time range of it.

If you want to delay whole Tween Player, you can disable it by default, then create a new empty Tween Player, use its arrived event to enable the previous one.

发件人: unitydev2019<mailto:notifications@github.com>
发送时间: 2020年8月18日 1:01
收件人: yuyang9119/UnityAssetStoreSupport<mailto:UnityAssetStoreSupport@noreply.github.com>
抄送: yuyang<mailto:yuyang9119@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [yuyang9119/UnityAssetStoreSupport] [TweenPlayer] - How to move button position by delta (#5)


Thank you! I will try it! But it is awesome if you can support the delta feature.
I have other questions:

  1.  When I setting the time to 1s and press play, I can not see the movement. It seems the loading screen makes that move stuck
(Because when I change the moving time to 2s, I can see that). How can I fix that? What is the best way to preload or cache the tween before it showing and start?
  2.  How can I set the delay from the start of an animation?
Thanks!

―

**Comment by unitydev2019** [comment]
Hi, @yuyang9119 Thank so much for your answer!
Could you please repost the image on the first answer? It is not showing on Github so I can not see where I can open context menu. Thank you so much!
Something like this showing on GitHub [cid:image001.png@01D674F5.D4AB6460]

**Comment by YT-GameMaker** [comment]
![d](https://user-images.githubusercontent.com/18855621/90537134-87144380-e1af-11ea-8308-0b8725d01f4e.png)

**Comment by unitydev2019** [comment]
Thank you!
